// flow-typed signature: 97effeb5ef2fe1dd92814072bce9b76a
// flow-typed version: <<STUB>>/react-desktop_v^0.2.14/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-desktop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-desktop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-desktop/macOs' {
  declare module.exports: any;
}

declare module 'react-desktop/osx' {
  declare module.exports: any;
}

declare module 'react-desktop/src/animation/bezierEasing' {
  declare module.exports: any;
}

declare module 'react-desktop/src/box/macOs/box' {
  declare module.exports: any;
}

declare module 'react-desktop/src/box/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/box/osx/box' {
  declare module.exports: any;
}

declare module 'react-desktop/src/box/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/button/macOs/button' {
  declare module.exports: any;
}

declare module 'react-desktop/src/button/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/button/osx/button' {
  declare module.exports: any;
}

declare module 'react-desktop/src/button/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/button/windows/button' {
  declare module.exports: any;
}

declare module 'react-desktop/src/button/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/macOs/checkbox' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/macOs/checkmark' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/osx/checkbox' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/osx/checkmark' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/windows/checkbox' {
  declare module.exports: any;
}

declare module 'react-desktop/src/checkbox/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/color' {
  declare module.exports: any;
}

declare module 'react-desktop/src/desktopComponent' {
  declare module.exports: any;
}

declare module 'react-desktop/src/desktopComponent/commonStyling' {
  declare module.exports: any;
}

declare module 'react-desktop/src/desktopComponent/placeholderStyle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/desktopComponent/windowFocus' {
  declare module.exports: any;
}

declare module 'react-desktop/src/dialog/macOs/dialog' {
  declare module.exports: any;
}

declare module 'react-desktop/src/dialog/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/dimension' {
  declare module.exports: any;
}

declare module 'react-desktop/src/label/macOs/label' {
  declare module.exports: any;
}

declare module 'react-desktop/src/label/osx/label' {
  declare module.exports: any;
}

declare module 'react-desktop/src/label/windows/label' {
  declare module.exports: any;
}

declare module 'react-desktop/src/link/macOs/link' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/footer/footer' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/footer/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/header/header' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/header/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/listView' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/row/row' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/row/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/section/header/header' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/section/header/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/section/section' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/section/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/separator/separator' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/separator/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/listView/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/masterDetailsView/windows/details/details' {
  declare module.exports: any;
}

declare module 'react-desktop/src/masterDetailsView/windows/item/item' {
  declare module.exports: any;
}

declare module 'react-desktop/src/masterDetailsView/windows/master/master' {
  declare module.exports: any;
}

declare module 'react-desktop/src/masterDetailsView/windows/masterDetailsView' {
  declare module.exports: any;
}

declare module 'react-desktop/src/masterDetailsView/windows/pane' {
  declare module.exports: any;
}

declare module 'react-desktop/src/monitor' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/item/content/content' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/item/item' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/item/title/title' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/navPane' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/pane/button/button' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/pane/item/item' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/pane/pane' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/pane/style/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/navPane/windows/style/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/pin/macOs/pin' {
  declare module.exports: any;
}

declare module 'react-desktop/src/pin/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/placeholderStyle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/macOs/progressCircle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/macOs/progressCircleAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/osx/progressCircle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/osx/progressCircleAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/windows/progressCircle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/windows/progressCircleAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/progressCircle/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/macOs/circle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/macOs/radio' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/osx/circle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/osx/radio' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/windows/circle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/windows/radio' {
  declare module.exports: any;
}

declare module 'react-desktop/src/radio/windows/styles/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/searchField/macOs/cancelAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/searchField/macOs/icons' {
  declare module.exports: any;
}

declare module 'react-desktop/src/searchField/macOs/searchField' {
  declare module.exports: any;
}

declare module 'react-desktop/src/searchField/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/macOs/item/item' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/macOs/segmentedControl' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/macOs/tabs/tab' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/macOs/tabs/tabs' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/osx/item/item' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/osx/segmentedControl' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/osx/style/style10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/osx/tabs/tab' {
  declare module.exports: any;
}

declare module 'react-desktop/src/segmentedControl/osx/tabs/tabs' {
  declare module.exports: any;
}

declare module 'react-desktop/src/splitView/macOs/pane/pane' {
  declare module.exports: any;
}

declare module 'react-desktop/src/splitView/macOs/pane/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/splitView/macOs/splitView' {
  declare module.exports: any;
}

declare module 'react-desktop/src/splitView/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/alignment' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/background/macOs' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/background/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/color/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/dimension' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/fontSize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/hidden' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/margin' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/padding' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/textAlign' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/theme' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/theme/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/width' {
  declare module.exports: any;
}

declare module 'react-desktop/src/styleHelper' {
  declare module.exports: any;
}

declare module 'react-desktop/src/text/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/text/macOs/text' {
  declare module.exports: any;
}

declare module 'react-desktop/src/text/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/text/windows/text' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/macOs/centerPlaceholderAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/macOs/focusRingAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/macOs/textInput' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/osx/textInput' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/textInput/windows/textInput' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/controls/close' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/controls/controls' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/controls/minimize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/controls/resize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/controls/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/macOs/titleBar' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/windows/controls/close' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/windows/controls/controls' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/windows/controls/maximize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/windows/controls/minimize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/titleBar/windows/titleBar' {
  declare module.exports: any;
}

declare module 'react-desktop/src/toolbar/macOs/nav/item/item' {
  declare module.exports: any;
}

declare module 'react-desktop/src/toolbar/macOs/nav/nav' {
  declare module.exports: any;
}

declare module 'react-desktop/src/toolbar/macOs/toolbar' {
  declare module.exports: any;
}

declare module 'react-desktop/src/toolbar/osx/toolbar' {
  declare module.exports: any;
}

declare module 'react-desktop/src/utils/mapStyles' {
  declare module.exports: any;
}

declare module 'react-desktop/src/view/macOs/view' {
  declare module.exports: any;
}

declare module 'react-desktop/src/view/view' {
  declare module.exports: any;
}

declare module 'react-desktop/src/view/windows/view' {
  declare module.exports: any;
}

declare module 'react-desktop/src/window/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/window/macOs/window' {
  declare module.exports: any;
}

declare module 'react-desktop/src/window/osx/styles/osx10_11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/window/osx/window' {
  declare module.exports: any;
}

declare module 'react-desktop/src/window/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/window/windows/window' {
  declare module.exports: any;
}

declare module 'react-desktop/src/windowFocus' {
  declare module.exports: any;
}

declare module 'react-desktop/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-desktop/index' {
  declare module.exports: $Exports<'react-desktop'>;
}
declare module 'react-desktop/index.js' {
  declare module.exports: $Exports<'react-desktop'>;
}
declare module 'react-desktop/macOs.js' {
  declare module.exports: $Exports<'react-desktop/macOs'>;
}
declare module 'react-desktop/osx.js' {
  declare module.exports: $Exports<'react-desktop/osx'>;
}
declare module 'react-desktop/src/animation/bezierEasing.js' {
  declare module.exports: $Exports<'react-desktop/src/animation/bezierEasing'>;
}
declare module 'react-desktop/src/box/macOs/box.js' {
  declare module.exports: $Exports<'react-desktop/src/box/macOs/box'>;
}
declare module 'react-desktop/src/box/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/box/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/box/osx/box.js' {
  declare module.exports: $Exports<'react-desktop/src/box/osx/box'>;
}
declare module 'react-desktop/src/box/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/box/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/button/macOs/button.js' {
  declare module.exports: $Exports<'react-desktop/src/button/macOs/button'>;
}
declare module 'react-desktop/src/button/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/button/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/button/osx/button.js' {
  declare module.exports: $Exports<'react-desktop/src/button/osx/button'>;
}
declare module 'react-desktop/src/button/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/button/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/button/windows/button.js' {
  declare module.exports: $Exports<'react-desktop/src/button/windows/button'>;
}
declare module 'react-desktop/src/button/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/button/windows/styles/windows10'>;
}
declare module 'react-desktop/src/checkbox/macOs/checkbox.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/macOs/checkbox'>;
}
declare module 'react-desktop/src/checkbox/macOs/checkmark.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/macOs/checkmark'>;
}
declare module 'react-desktop/src/checkbox/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/checkbox/osx/checkbox.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/osx/checkbox'>;
}
declare module 'react-desktop/src/checkbox/osx/checkmark.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/osx/checkmark'>;
}
declare module 'react-desktop/src/checkbox/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/checkbox/windows/checkbox.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/windows/checkbox'>;
}
declare module 'react-desktop/src/checkbox/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/checkbox/windows/styles/windows10'>;
}
declare module 'react-desktop/src/color.js' {
  declare module.exports: $Exports<'react-desktop/src/color'>;
}
declare module 'react-desktop/src/desktopComponent.js' {
  declare module.exports: $Exports<'react-desktop/src/desktopComponent'>;
}
declare module 'react-desktop/src/desktopComponent/commonStyling.js' {
  declare module.exports: $Exports<'react-desktop/src/desktopComponent/commonStyling'>;
}
declare module 'react-desktop/src/desktopComponent/placeholderStyle.js' {
  declare module.exports: $Exports<'react-desktop/src/desktopComponent/placeholderStyle'>;
}
declare module 'react-desktop/src/desktopComponent/windowFocus.js' {
  declare module.exports: $Exports<'react-desktop/src/desktopComponent/windowFocus'>;
}
declare module 'react-desktop/src/dialog/macOs/dialog.js' {
  declare module.exports: $Exports<'react-desktop/src/dialog/macOs/dialog'>;
}
declare module 'react-desktop/src/dialog/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/dialog/macOs/style/10.11'>;
}
declare module 'react-desktop/src/dimension.js' {
  declare module.exports: $Exports<'react-desktop/src/dimension'>;
}
declare module 'react-desktop/src/label/macOs/label.js' {
  declare module.exports: $Exports<'react-desktop/src/label/macOs/label'>;
}
declare module 'react-desktop/src/label/osx/label.js' {
  declare module.exports: $Exports<'react-desktop/src/label/osx/label'>;
}
declare module 'react-desktop/src/label/windows/label.js' {
  declare module.exports: $Exports<'react-desktop/src/label/windows/label'>;
}
declare module 'react-desktop/src/link/macOs/link.js' {
  declare module.exports: $Exports<'react-desktop/src/link/macOs/link'>;
}
declare module 'react-desktop/src/listView/macOs/footer/footer.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/footer/footer'>;
}
declare module 'react-desktop/src/listView/macOs/footer/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/footer/style/10.11'>;
}
declare module 'react-desktop/src/listView/macOs/header/header.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/header/header'>;
}
declare module 'react-desktop/src/listView/macOs/header/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/header/style/10.11'>;
}
declare module 'react-desktop/src/listView/macOs/listView.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/listView'>;
}
declare module 'react-desktop/src/listView/macOs/row/row.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/row/row'>;
}
declare module 'react-desktop/src/listView/macOs/row/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/row/style/10.11'>;
}
declare module 'react-desktop/src/listView/macOs/section/header/header.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/section/header/header'>;
}
declare module 'react-desktop/src/listView/macOs/section/header/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/section/header/style/10.11'>;
}
declare module 'react-desktop/src/listView/macOs/section/section.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/section/section'>;
}
declare module 'react-desktop/src/listView/macOs/section/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/section/style/10.11'>;
}
declare module 'react-desktop/src/listView/macOs/separator/separator.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/separator/separator'>;
}
declare module 'react-desktop/src/listView/macOs/separator/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/separator/style/10.11'>;
}
declare module 'react-desktop/src/listView/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/listView/macOs/style/10.11'>;
}
declare module 'react-desktop/src/masterDetailsView/windows/details/details.js' {
  declare module.exports: $Exports<'react-desktop/src/masterDetailsView/windows/details/details'>;
}
declare module 'react-desktop/src/masterDetailsView/windows/item/item.js' {
  declare module.exports: $Exports<'react-desktop/src/masterDetailsView/windows/item/item'>;
}
declare module 'react-desktop/src/masterDetailsView/windows/master/master.js' {
  declare module.exports: $Exports<'react-desktop/src/masterDetailsView/windows/master/master'>;
}
declare module 'react-desktop/src/masterDetailsView/windows/masterDetailsView.js' {
  declare module.exports: $Exports<'react-desktop/src/masterDetailsView/windows/masterDetailsView'>;
}
declare module 'react-desktop/src/masterDetailsView/windows/pane.js' {
  declare module.exports: $Exports<'react-desktop/src/masterDetailsView/windows/pane'>;
}
declare module 'react-desktop/src/monitor.js' {
  declare module.exports: $Exports<'react-desktop/src/monitor'>;
}
declare module 'react-desktop/src/navPane/windows/item/content/content.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/item/content/content'>;
}
declare module 'react-desktop/src/navPane/windows/item/item.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/item/item'>;
}
declare module 'react-desktop/src/navPane/windows/item/title/title.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/item/title/title'>;
}
declare module 'react-desktop/src/navPane/windows/navPane.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/navPane'>;
}
declare module 'react-desktop/src/navPane/windows/pane/button/button.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/pane/button/button'>;
}
declare module 'react-desktop/src/navPane/windows/pane/item/item.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/pane/item/item'>;
}
declare module 'react-desktop/src/navPane/windows/pane/pane.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/pane/pane'>;
}
declare module 'react-desktop/src/navPane/windows/pane/style/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/pane/style/windows10'>;
}
declare module 'react-desktop/src/navPane/windows/style/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/navPane/windows/style/windows10'>;
}
declare module 'react-desktop/src/pin/macOs/pin.js' {
  declare module.exports: $Exports<'react-desktop/src/pin/macOs/pin'>;
}
declare module 'react-desktop/src/pin/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/pin/macOs/style/10.11'>;
}
declare module 'react-desktop/src/placeholderStyle.js' {
  declare module.exports: $Exports<'react-desktop/src/placeholderStyle'>;
}
declare module 'react-desktop/src/progressCircle/macOs/progressCircle.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/macOs/progressCircle'>;
}
declare module 'react-desktop/src/progressCircle/macOs/progressCircleAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/macOs/progressCircleAnimation'>;
}
declare module 'react-desktop/src/progressCircle/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/progressCircle/osx/progressCircle.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/osx/progressCircle'>;
}
declare module 'react-desktop/src/progressCircle/osx/progressCircleAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/osx/progressCircleAnimation'>;
}
declare module 'react-desktop/src/progressCircle/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/progressCircle/windows/progressCircle.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/windows/progressCircle'>;
}
declare module 'react-desktop/src/progressCircle/windows/progressCircleAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/windows/progressCircleAnimation'>;
}
declare module 'react-desktop/src/progressCircle/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/progressCircle/windows/styles/windows10'>;
}
declare module 'react-desktop/src/radio/macOs/circle.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/macOs/circle'>;
}
declare module 'react-desktop/src/radio/macOs/radio.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/macOs/radio'>;
}
declare module 'react-desktop/src/radio/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/radio/osx/circle.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/osx/circle'>;
}
declare module 'react-desktop/src/radio/osx/radio.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/osx/radio'>;
}
declare module 'react-desktop/src/radio/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/radio/windows/circle.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/windows/circle'>;
}
declare module 'react-desktop/src/radio/windows/radio.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/windows/radio'>;
}
declare module 'react-desktop/src/radio/windows/styles/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/radio/windows/styles/windows'>;
}
declare module 'react-desktop/src/searchField/macOs/cancelAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/searchField/macOs/cancelAnimation'>;
}
declare module 'react-desktop/src/searchField/macOs/icons.js' {
  declare module.exports: $Exports<'react-desktop/src/searchField/macOs/icons'>;
}
declare module 'react-desktop/src/searchField/macOs/searchField.js' {
  declare module.exports: $Exports<'react-desktop/src/searchField/macOs/searchField'>;
}
declare module 'react-desktop/src/searchField/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/searchField/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/segmentedControl/macOs/item/item.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/macOs/item/item'>;
}
declare module 'react-desktop/src/segmentedControl/macOs/segmentedControl.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/macOs/segmentedControl'>;
}
declare module 'react-desktop/src/segmentedControl/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/macOs/style/10.11'>;
}
declare module 'react-desktop/src/segmentedControl/macOs/tabs/tab.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/macOs/tabs/tab'>;
}
declare module 'react-desktop/src/segmentedControl/macOs/tabs/tabs.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/macOs/tabs/tabs'>;
}
declare module 'react-desktop/src/segmentedControl/osx/item/item.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/osx/item/item'>;
}
declare module 'react-desktop/src/segmentedControl/osx/segmentedControl.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/osx/segmentedControl'>;
}
declare module 'react-desktop/src/segmentedControl/osx/style/style10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/osx/style/style10_11'>;
}
declare module 'react-desktop/src/segmentedControl/osx/tabs/tab.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/osx/tabs/tab'>;
}
declare module 'react-desktop/src/segmentedControl/osx/tabs/tabs.js' {
  declare module.exports: $Exports<'react-desktop/src/segmentedControl/osx/tabs/tabs'>;
}
declare module 'react-desktop/src/splitView/macOs/pane/pane.js' {
  declare module.exports: $Exports<'react-desktop/src/splitView/macOs/pane/pane'>;
}
declare module 'react-desktop/src/splitView/macOs/pane/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/splitView/macOs/pane/style/10.11'>;
}
declare module 'react-desktop/src/splitView/macOs/splitView.js' {
  declare module.exports: $Exports<'react-desktop/src/splitView/macOs/splitView'>;
}
declare module 'react-desktop/src/splitView/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/splitView/macOs/style/10.11'>;
}
declare module 'react-desktop/src/style/alignment.js' {
  declare module.exports: $Exports<'react-desktop/src/style/alignment'>;
}
declare module 'react-desktop/src/style/background/macOs.js' {
  declare module.exports: $Exports<'react-desktop/src/style/background/macOs'>;
}
declare module 'react-desktop/src/style/background/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/style/background/windows'>;
}
declare module 'react-desktop/src/style/color/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/style/color/windows'>;
}
declare module 'react-desktop/src/style/dimension.js' {
  declare module.exports: $Exports<'react-desktop/src/style/dimension'>;
}
declare module 'react-desktop/src/style/fontSize.js' {
  declare module.exports: $Exports<'react-desktop/src/style/fontSize'>;
}
declare module 'react-desktop/src/style/hidden.js' {
  declare module.exports: $Exports<'react-desktop/src/style/hidden'>;
}
declare module 'react-desktop/src/style/margin.js' {
  declare module.exports: $Exports<'react-desktop/src/style/margin'>;
}
declare module 'react-desktop/src/style/padding.js' {
  declare module.exports: $Exports<'react-desktop/src/style/padding'>;
}
declare module 'react-desktop/src/style/textAlign.js' {
  declare module.exports: $Exports<'react-desktop/src/style/textAlign'>;
}
declare module 'react-desktop/src/style/theme.js' {
  declare module.exports: $Exports<'react-desktop/src/style/theme'>;
}
declare module 'react-desktop/src/style/theme/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/style/theme/windows'>;
}
declare module 'react-desktop/src/style/width.js' {
  declare module.exports: $Exports<'react-desktop/src/style/width'>;
}
declare module 'react-desktop/src/styleHelper.js' {
  declare module.exports: $Exports<'react-desktop/src/styleHelper'>;
}
declare module 'react-desktop/src/text/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/text/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/text/macOs/text.js' {
  declare module.exports: $Exports<'react-desktop/src/text/macOs/text'>;
}
declare module 'react-desktop/src/text/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/text/windows/styles/windows10'>;
}
declare module 'react-desktop/src/text/windows/text.js' {
  declare module.exports: $Exports<'react-desktop/src/text/windows/text'>;
}
declare module 'react-desktop/src/textInput/macOs/centerPlaceholderAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/macOs/centerPlaceholderAnimation'>;
}
declare module 'react-desktop/src/textInput/macOs/focusRingAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/macOs/focusRingAnimation'>;
}
declare module 'react-desktop/src/textInput/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/textInput/macOs/textInput.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/macOs/textInput'>;
}
declare module 'react-desktop/src/textInput/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/textInput/osx/textInput.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/osx/textInput'>;
}
declare module 'react-desktop/src/textInput/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/windows/styles/windows10'>;
}
declare module 'react-desktop/src/textInput/windows/textInput.js' {
  declare module.exports: $Exports<'react-desktop/src/textInput/windows/textInput'>;
}
declare module 'react-desktop/src/titleBar/macOs/controls/close.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/controls/close'>;
}
declare module 'react-desktop/src/titleBar/macOs/controls/controls.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/controls/controls'>;
}
declare module 'react-desktop/src/titleBar/macOs/controls/minimize.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/controls/minimize'>;
}
declare module 'react-desktop/src/titleBar/macOs/controls/resize.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/controls/resize'>;
}
declare module 'react-desktop/src/titleBar/macOs/controls/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/controls/styles/10.11'>;
}
declare module 'react-desktop/src/titleBar/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/titleBar/macOs/titleBar.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/macOs/titleBar'>;
}
declare module 'react-desktop/src/titleBar/windows/controls/close.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/windows/controls/close'>;
}
declare module 'react-desktop/src/titleBar/windows/controls/controls.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/windows/controls/controls'>;
}
declare module 'react-desktop/src/titleBar/windows/controls/maximize.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/windows/controls/maximize'>;
}
declare module 'react-desktop/src/titleBar/windows/controls/minimize.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/windows/controls/minimize'>;
}
declare module 'react-desktop/src/titleBar/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/windows/styles/windows10'>;
}
declare module 'react-desktop/src/titleBar/windows/titleBar.js' {
  declare module.exports: $Exports<'react-desktop/src/titleBar/windows/titleBar'>;
}
declare module 'react-desktop/src/toolbar/macOs/nav/item/item.js' {
  declare module.exports: $Exports<'react-desktop/src/toolbar/macOs/nav/item/item'>;
}
declare module 'react-desktop/src/toolbar/macOs/nav/nav.js' {
  declare module.exports: $Exports<'react-desktop/src/toolbar/macOs/nav/nav'>;
}
declare module 'react-desktop/src/toolbar/macOs/toolbar.js' {
  declare module.exports: $Exports<'react-desktop/src/toolbar/macOs/toolbar'>;
}
declare module 'react-desktop/src/toolbar/osx/toolbar.js' {
  declare module.exports: $Exports<'react-desktop/src/toolbar/osx/toolbar'>;
}
declare module 'react-desktop/src/utils/mapStyles.js' {
  declare module.exports: $Exports<'react-desktop/src/utils/mapStyles'>;
}
declare module 'react-desktop/src/view/macOs/view.js' {
  declare module.exports: $Exports<'react-desktop/src/view/macOs/view'>;
}
declare module 'react-desktop/src/view/view.js' {
  declare module.exports: $Exports<'react-desktop/src/view/view'>;
}
declare module 'react-desktop/src/view/windows/view.js' {
  declare module.exports: $Exports<'react-desktop/src/view/windows/view'>;
}
declare module 'react-desktop/src/window/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/window/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/window/macOs/window.js' {
  declare module.exports: $Exports<'react-desktop/src/window/macOs/window'>;
}
declare module 'react-desktop/src/window/osx/styles/osx10_11.js' {
  declare module.exports: $Exports<'react-desktop/src/window/osx/styles/osx10_11'>;
}
declare module 'react-desktop/src/window/osx/window.js' {
  declare module.exports: $Exports<'react-desktop/src/window/osx/window'>;
}
declare module 'react-desktop/src/window/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/window/windows/styles/windows10'>;
}
declare module 'react-desktop/src/window/windows/window.js' {
  declare module.exports: $Exports<'react-desktop/src/window/windows/window'>;
}
declare module 'react-desktop/src/windowFocus.js' {
  declare module.exports: $Exports<'react-desktop/src/windowFocus'>;
}
declare module 'react-desktop/windows.js' {
  declare module.exports: $Exports<'react-desktop/windows'>;
}
